---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: Ванька TV
background: /images/image.jpg

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
